# Generated by Django 4.2.1 on 2023-05-27 20:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0002_alter_place_geom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="geom",
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
