# Generated by Django 4.2.1 on 2023-05-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0004_alter_place_geom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
